#ifndef __LV2_SYSMODULE_H__
#define __LV2_SYSMODULE_H__

#include <ppu-types.h>

#ifdef __cplusplus
extern "C" {
#endif

/* constants */
#define CELL_SYSMODULE_OK                             0x00
#define CELL_SYSMODULE_LOADED                         0x00
#define CELL_SYSMODULE_ERR_DUPLICATE                  0x80012001 /* already loaded */
#define CELL_SYSMODULE_ERR_UNKNOWN                    0x80012002 /* unknown prx */
#define CELL_SYSMODULE_ERR_UNLOADED                   0x80012003 /* already unloaded */
#define CELL_SYSMODULE_ERR_INVALID_MEM                0x80012004 /* invalid memory container */
#define CELL_SYSMODULE_ERR_FATAL                      0x800120ff /* call failed */


typedef enum
{
	CELL_SYSMODULE_NET = 0x0,
	CELL_SYSMODULE_HTTP = 0x1,
	CELL_SYSMODULE_HTTP_UTIL = 0x02,
	CELL_SYSMODULE_SSL = 0x03,
	CELL_SYSMODULE_HTTPS = 0x04,

	CELL_SYSMODULE_VDEC = 0x05,
	CELL_SYSMODULE_ADEC = 0x06,
	CELL_SYSMODULE_DMUX = 0x07,
	CELL_SYSMODULE_VPOST = 0x08,
	CELL_SYSMODULE_RTC = 0x09,

	CELL_SYSMODULE_SPURS = 0x0a,
	CELL_SYSMODULE_OVIS = 0x0b,
	CELL_SYSMODULE_SHEAP = 0x0c,

	CELL_SYSMODULE_SYNC = 0x0d,
	CELL_SYSMODULE_FS = 0x0e,
	CELL_SYSMODULE_JPGDEC = 0x0f,
	CELL_SYSMODULE_CELL_GCM_SYS = 0x10,
	CELL_SYSMODULE_AUDIO = 0x11,
	CELL_SYSMODULE_PAMF = 0x12,
	CELL_SYSMODULE_ATRAC3 = 0x13,
	CELL_SYSMODULE_NETCTL = 0x14,
	CELL_SYSMODULE_SYSUTIL = 0x15,
	CELL_SYSMODULE_SYSUTIL_NP = 0x16,
	CELL_SYSMODULE_IO = 0x17,
	CELL_SYSMODULE_PNGDEC = 0x18,
	CELL_SYSMODULE_FONT = 0x19,
	CELL_SYSMODULE_FONTFT = 0x1a,
	CELL_SYSMODULE_FREETYPE = 0x1b,
	CELL_SYSMODULE_USB = 0x1c,
	CELL_SYSMODULE_SAIL = 0x1d,
	CELL_SYSMODULE_RESC = 0x1f,

	CELL_SYSMODULE_DAISY = 0x20,
	CELL_SYSMODULE_KEY2CHAR = 0x21,
	CELL_SYSMODULE_MIC = 0x22,
	CELL_SYSMODULE_CAMERA = 0x23,

	CELL_SYSMODULE_VDEC_MPEG2 = 0x24,
	CELL_SYSMODULE_VDEC_H264 = 0x25,
	CELL_SYSMODULE_ADEC_LPCM = 0x26,
	CELL_SYSMODULE_ADEC_AC3 = 0x27,
	CELL_SYSMODULE_ADEC_ATX = 0x28,
	CELL_SYSMODULE_ADEC_AT3 = 0x29,
	CELL_SYSMODULE_ADEC_PAMF = 0x2a,

	CELL_SYSMODULE_LV2DBG = 0x2e,

	CELL_SYSMODULE_USERINFO = 0x32,
	CELL_SYSMODULE_SAVEDATA = 0x33,

	CELL_SYSMODULE_VDEC_DIVX = 0x3c,
	CELL_SYSMODULE_JPGENC = 0x3d,
	CELL_SYSMODULE_FREETYPE_TT = 0x40,
	CELL_SYSMODULE_FIBER = 0x43,
	CELL_SYSMODULE_VOICE = 0x46,
	CELL_SYSMODULE_ADEC_CELP8 = 0x47,
	CELL_SYSMODULE_CELP8ENC = 0x48,
	CELL_SYSMODULE_MUSIC2 = 0x4a,
	CELL_SYSMODULE_MUSIC_DEC = 0x4f,

	CELL_SYSMODULE_SPURS_JQ = 0x50,
	CELL_SYSMODULE_PNGENC = 0x52,
	CELL_SYSMODULE_MUSIC_DEC2 = 0x53,
	CELL_SYSMODULE_SYNC2 = 0x55,
	CELL_SYSMODULE_RUDP = 0x57,
	CELL_SYSMODULE_GEM = 0x5a,
	CELL_SYSMODULE_GIFDEC = 0xf0a0,
	CELL_SYSMODULE_ADEC_MP3 = 0xf01e,
} CellSysmoduleModuleId;


s32 cellSysmoduleLoadModule(CellSysmoduleModuleId id);
s32 cellSysmoduleUnloadModule(CellSysmoduleModuleId id);
s32 cellSysmoduleIsLoaded(CellSysmoduleModuleId id);


#ifdef __cplusplus
	}
#endif

#endif
