#ifndef __LV2_FONTSET_H__
#define __LV2_FONTSET_H__

#define CELL_FONT_TYPE_RODIN_SANS_SERIF_LATIN              		    0x00000000
#define CELL_FONT_TYPE_MATISSE_SERIF_LATIN                 		    0x00000020
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_JAPANESE            		    0x00000008
#define CELL_FONT_TYPE_YD_GOTHIC_KOREAN                    		    0x0000000c

#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_JP_SET              		    0x00000100
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_LATIN_SET           		    0x00000101
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_DFHEI5_SET				0x00000108 //SDK1.60-
#define CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_DFHEI5_RODIN_SET		    0x00000109 //SDK1.60-
#define CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_TCH_SET			0x0000010a //SDK1.60-
#define CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN_TCH_SET	    0x0000010b //SDK1.60-
#define CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_SCH_SET			0x0000010c //SDK1.60-
#define CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN_SCH_SET	    0x0000010d //SDK1.60-

//SDK1.00-
// ==========================================================================================================
#define CELL_FONT_TYPE_DEFAULT_GOTHIC_SET						    CELL_FONT_TYPE_NEWRODIN_GOTHIC_LATIN_SET 
#define CELL_FONT_TYPE_DEFAULT_GOTHIC_LATIN_SET					    CELL_FONT_TYPE_NEWRODIN_GOTHIC_LATIN_SET 
#define CELL_FONT_TYPE_DEFAULT_GOTHIC_JP_SET						CELL_FONT_TYPE_NEWRODIN_GOTHIC_JP_SET    
#define CELL_FONT_TYPE_DEFAULT_SANS_SERIF						    CELL_FONT_TYPE_RODIN_SANS_SERIF_LATIN    
#define CELL_FONT_TYPE_DEFAULT_SERIF								CELL_FONT_TYPE_MATISSE_SERIF_LATIN       

//SDK1.60-
// ==========================================================================================================
#define	CELL_FONT_TYPE_GOTHIC_JAPANESE_CJK_JP_SET				    CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_DFHEI5_SET
#define	CELL_FONT_TYPE_GOTHIC_JAPANESE_CJK_LATIN_SET				CELL_FONT_TYPE_NEWRODIN_GOTHIC_YG_DFHEI5_RODIN_SET
#define	CELL_FONT_TYPE_GOTHIC_TCHINESE_CJK_JP_SET				    CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_TCH_SET
#define CELL_FONT_TYPE_GOTHIC_TCHINESE_CJK_LATIN_SET				CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN_TCH_SET
#define CELL_FONT_TYPE_GOTHIC_SCHINESE_CJK_JP_SET				    CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_SCH_SET
#define CELL_FONT_TYPE_GOTHIC_SCHINESE_CJK_LATIN_SET				CELL_FONT_TYPE_DFHEI5_GOTHIC_YG_NEWRODIN_RODIN_SCH_SET
// ----------------------------------------------------------------------------------------------------------

//-----------------------------------
#define CELL_FONT_MAP_FONT										0x0
#define CELL_FONT_MAP_UNICODE									0x1
//-----------------------------------

#endif
